#index:
#    path: /
#    controller: App\Controller\DefaultController::index


users:
    path: /api/users
    controller: App\Controller\UserController::getUsers

register:
    path: /api/register
    controller: App\Controller\RegisterUserController::registerUser

login:
    path: /api/login
    controller: App\Controller\LogginController::login

getMyAssets:
    path: /api/getMyAsset
    controller: App\Controller\AssetController::getMyAssets

edditAsset:
    path: /api/editAsset
    controller: App\Controller\AssetController::editAsset

addAsset:
    path: /api/addAsset
    controller: App\Controller\AssetController::addAsset